"""Point-in-time index membership: who was in the universe, on the day.

The file this reads is generated by `tools/build_universe.py` and committed, because it
is data rather than a cache. Regenerating it changes every cross-sectional result built
on it, so that should be a deliberate act with a diff, not something that happens
silently on a new machine.

WHAT IT BUYS, as a number. Across 2018-08 to 2026-07 the S&P 500 held 503-505 names at
any moment and 681 distinct names in total. A universe built from today's constituents
would therefore be missing 178 of them -- 26% of the real sample -- and they are not a
random 26%. They are the acquired, the demoted and the failed: SIVB and SBNY leave after
February 2023, FRC after April 2023, TWTR after September 2022. Those are precisely the
names a momentum or 52-week-high strategy would have been holding on the way down, and
dropping them is how a backtest reports an edge that never existed.

WHAT IT DOES NOT BUY. This is not CRSP. The limitations are recorded in the generated
file's own header so they travel with the data, and they are restated in
PREREGISTRATION.md rather than left in a docstring: editor lag of a few days around index
changes, no CIK-level continuity so a reused ticker is indistinguishable, and month-end
sampling so a name added and dropped inside one month is invisible.
"""

from __future__ import annotations

import csv
import functools
from dataclasses import dataclass
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_PATH = REPO_ROOT / "universe" / "sp500_membership.csv"


class UniverseError(Exception):
    """The membership file is missing or malformed."""


@dataclass(frozen=True)
class Membership:
    """Month-end snapshots of index membership."""

    snapshots: dict[date, frozenset[str]]

    @property
    def dates(self) -> list[date]:
        return sorted(self.snapshots)

    def as_of(self, when: date) -> frozenset[str]:
        """Members at the most recent snapshot AT OR BEFORE `when`.

        At or before, never the nearest. Taking the nearest snapshot in either
        direction would let a name that joins the index next month trade this month --
        an invisible lookahead biased exactly toward the names about to perform well
        enough to be added.

        Before the first snapshot the answer is the empty set, not the earliest
        snapshot: we do not know who was in the index then, and guessing would be worse
        than declining.
        """
        keys = [d for d in self.snapshots if d <= when]
        return self.snapshots[max(keys)] if keys else frozenset()

    def all_tickers(self) -> frozenset[str]:
        """Every name that was ever a member. This is the backfill list."""
        out: set[str] = set()
        for names in self.snapshots.values():
            out |= names
        return frozenset(out)

    def tenure(self, ticker: str) -> tuple[date, date] | None:
        """First and last snapshot containing `ticker`, or None if never a member."""
        seen = [d for d, names in self.snapshots.items() if ticker in names]
        return (min(seen), max(seen)) if seen else None

    def survivorship_gap(self) -> tuple[int, int]:
        """(names ever a member, names still a member at the last snapshot).

        The gap between these two is the size of the bias a today's-constituents
        universe would have introduced. Reported alongside results rather than left
        implicit, because it is the single most important caveat on any cross-sectional
        number produced here.
        """
        if not self.snapshots:
            return (0, 0)
        return (len(self.all_tickers()), len(self.snapshots[max(self.snapshots)]))


def load(path: Path | str | None = None) -> Membership:
    """Read the committed membership file.

    Refuses an empty or unparseable file rather than returning an empty universe. An
    empty universe silently produces zero cross-sectional signals, which looks exactly
    like a strategy that never triggered.
    """
    p = Path(path) if path else DEFAULT_PATH
    if not p.exists():
        raise UniverseError(
            f"{p} not found -- run `uv run python tools/build_universe.py` to generate it"
        )

    snapshots: dict[date, set[str]] = {}
    with p.open() as fh:
        rows = csv.DictReader(line for line in fh if not line.startswith("#"))
        for row in rows:
            try:
                when = date.fromisoformat(row["as_of"])
            except (KeyError, ValueError) as exc:
                raise UniverseError(f"{p}: bad row {row!r}") from exc
            snapshots.setdefault(when, set()).add(row["ticker"])

    if not snapshots:
        raise UniverseError(f"{p} contained no membership rows")
    return Membership({d: frozenset(names) for d, names in snapshots.items()})


@functools.cache
def default() -> Membership:
    """The committed universe, loaded once per process."""
    return load()


def to_alpaca(ticker: str) -> str:
    """Wikipedia writes class shares as BRK.B; Alpaca wants BRK.B too, but some
    sources use BRK-B. Normalised in one place so the mapping is auditable rather
    than scattered through the fetch loop."""
    return ticker.strip().upper()
